import type { LoanSnapshot } from "../types/loans";

export function createBlankLoanSnapshot(todayValue: string): LoanSnapshot {
  return {
    accountType: "loan",
    cardMinimumMode: "percent",
    cardMinimumPercent: "2",
    cardMinimumFloor: "25",
    postPromoMinimumMode: "percent",
    postPromoMinimumPercent: "2",
    postPromoMinimumFloor: "25",
    postPromoFixedMinimum: "",
    cardStatementDate: "",
    creditCardTransactions: [],
    activeView: "assumed",
    additionalMonthlyPayment: "0",
    aprPercent: "",
    dayCountBasis: "actual-year",
    deletedHelperRowIds: [],
    dueDay: "1",
    editingPaymentAmount: "",
    editingPaymentDate: "",
    editingPaymentId: "",
    editingPaymentLabel: "",
    firstPaymentDate: "",
    helperActionError: "",
    helperAdjustmentAmount: "",
    helperAdjustmentDueDay: "",
    helperAdjustmentFromMonth: "",
    helperAdjustmentToMonth: "",
    helperBulkMode: "pause",
    helperDueDayChanges: [],
    helperPauseFromMonth: "",
    helperPauseMode: "accrues",
    helperPausePeriods: [],
    helperPauseToMonth: "",
    helperPaymentAmountOverrides: {},
    helperRecurringChanges: [],
    loanName: "",
    minimumPayment: "",
    moveWeekend: false,
    newOneOffAmount: "",
    newOneOffDate: "",
    newOneOffLabel: "Extra payment",
    newWhatIfAmount: "",
    newWhatIfDate: "",
    newWhatIfLabel: "Anticipated one-time payment",
    oneOffPayments: [],
    promoType: "none",
    promoEndDate: "",
    paymentDateOverrides: {},
    paymentLabelOverrides: {},
    roundDailyInterest: false,
    showAmortization: false,
    showComparisonDetails: false,
    showFutureDetails: false,
    showHelperAmortization: false,
    showHistoricalDetails: false,
    showLifetimeDetails: false,
    startingPrincipal: "",
    startingPrincipalDate: "",
    targetDate: todayValue,
    whatIfActionError: "",
    whatIfAdjustmentAmount: "",
    whatIfAdjustmentDate: "",
    whatIfAdjustmentDueDay: "",
    whatIfAdjustmentEndDate: "",
    whatIfDueDayChanges: [],
    whatIfEntryMode: "one-time",
    whatIfPauseFromMonth: "",
    whatIfPauseMode: "accrues",
    whatIfPausePeriods: [],
    whatIfPauseToMonth: "",
    whatIfPayments: [],
    whatIfRecurringChanges: [],
  };
}
