import type { Dispatch, RefObject, SetStateAction } from "react";
import type { ThemeDefinition, ThemeId } from "../constants/theme";
import type { DayCountBasis, DueDayChange, FutureRecurringChange, PausePeriod, PaymentEvent, SavedLoanRecord, ScheduleResult } from "./loans";
import type { buildSchedule } from "../calculations/loans/schedule";
import type { UserProfile } from "./profile";

export type HeaderLoan = { id: string; name: string; balance: number; apr: number; minimum: number };
export type HeaderProjection = { startingTotal: number; payoffDate: Date | null };

/** Shared boundary contract for simulator state, projections, and actions. */
export interface LoanSimulatorRuntime {
  [key: string]: unknown;
  activePage: "overview" | "simulator" | "paycheck" | "budget" | "profile";
  activeLoanTab: "details" | "transactions" | "history" | "whatif";
  activeView: "assumed" | "history" | "whatif";
  currentLoanId: string | null;
  creditCardTransactions: PaymentEvent[];
  currentTheme: ThemeDefinition;
  deleteAccountConfirmOpen: boolean;
  deleteCurrentUserProfile?: () => void | Promise<void>;
  deleteLoan?: (id: string) => void | Promise<void>;
  displayName: string;
  firstName: string;
  headerLoans?: HeaderLoan[];
  headerProjection?: HeaderProjection;
  headerProgress?: number;
  currentUserId: string | null;
  currentUser: UserProfile | null;
  profileMenuOpen: boolean;
  setProfileMenuOpen: Dispatch<SetStateAction<boolean>>;
  profileDraftName: string;
  setProfileDraftName: Dispatch<SetStateAction<string>>;
  profileDraftEmail: string;
  setProfileDraftEmail: Dispatch<SetStateAction<string>>;
  profileStatus: string;
  passwordResetCodeInput: string;
  setPasswordResetCodeInput: Dispatch<SetStateAction<string>>;
  passwordResetNewPassword: string;
  setPasswordResetNewPassword: Dispatch<SetStateAction<string>>;
  passwordResetConfirmPassword: string;
  setPasswordResetConfirmPassword: Dispatch<SetStateAction<string>>;
  logoutUser?: () => void | Promise<void>;
  saveProfileDetails?: () => void | Promise<void>;
  applyThemeToProfile?: (themeId: ThemeId) => void | Promise<void>;
  sendPasswordResetEmail?: () => void | Promise<void>;
  applyPasswordReset?: () => void | Promise<void>;
  loanName: string;
  loanSidebarCollapsed: boolean;
  profileInitial: string;
  savedLoans: SavedLoanRecord[];
  saveStatus: string;
  setActivePage: Dispatch<SetStateAction<LoanSimulatorRuntime["activePage"]>>;
  setCreditCardTransactions: Dispatch<SetStateAction<PaymentEvent[]>>;
  setDeleteAccountConfirmOpen: Dispatch<SetStateAction<boolean>>;
  setActiveLoanTab: Dispatch<SetStateAction<LoanSimulatorRuntime["activeLoanTab"]>>;
  setActiveView: Dispatch<SetStateAction<LoanSimulatorRuntime["activeView"]>>;
  setLoanSidebarCollapsed: Dispatch<SetStateAction<boolean>>;
  startNewLoan?: (type?: "loan" | "credit-card") => void;
  loadSavedLoan?: (id: string) => void;
  profileMenuRef: RefObject<HTMLDivElement | null>;
  startingPrincipalDate: string;
  minimumPayment: string;
  additionalMonthlyPayment: string;
  dueDay: string;
  targetDate: string;
  moveWeekend: boolean;
  roundDailyInterest: boolean;
  dayCountBasis: DayCountBasis;
  oneOffPayments: PaymentEvent[];
  helperPausePeriods: PausePeriod[];
  helperRecurringChanges: FutureRecurringChange[];
  helperDueDayChanges: DueDayChange[];
  deletedHelperRowIds: string[];
  helperPaymentAmountOverrides: Record<string, string>;
  paymentDateOverrides: Record<string, string>;
  paymentLabelOverrides: Record<string, string>;
  whatIfPayments: PaymentEvent[];
  whatIfRecurringChanges: FutureRecurringChange[];
  whatIfPausePeriods: PausePeriod[];
  whatIfDueDayChanges: DueDayChange[];
  deferredStartingPrincipal: string;
  deferredStartingPrincipalDate: string;
  deferredFirstPaymentDate: string;
  deferredAdditionalMonthlyPayment: string;
  deferredAprPercent: string;
  deferredDueDay: string;
  deferredTargetDate: string;
  effectiveMinimumPayment: string;
  totalMonthlyPayment: string;
  buildProjection: (...args: Parameters<typeof buildSchedule>) => ScheduleResult;
  todayDate: Date;
  todayValue: string;
}
