import type { Dispatch, RefObject, SetStateAction } from "react";
import type { ThemeDefinition, ThemeId } from "../constants/theme";
import type { DayCountBasis, DueDayChange, FutureRecurringChange, LoanSnapshot, PausePeriod, PaymentEvent, SavedLoanRecord, ScheduleResult, SerializedDueDayChange, SerializedFutureRecurringChange, SerializedPausePeriod, SerializedPaymentEvent } from "./loans";
import type { buildSchedule } from "../calculations/loans/schedule";
import type { UserProfile } from "./profile";

export type HeaderLoan = { id: string; name: string; balance: number; apr: number; minimum: number };
export type HeaderProjection = { startingTotal: number; payoffDate: Date | null };

/** Shared boundary contract for simulator state, projections, and actions. */
export interface LoanSimulatorRuntime {
  [key: string]: unknown;
  activePage: "overview" | "simulator" | "paycheck" | "budget" | "profile";
  activeLoanTab: "details" | "transactions" | "history" | "whatif";
  activeView: "assumed" | "history" | "whatif";
  currentLoanId: string | null;
  creditCardTransactions: PaymentEvent[];
  currentTheme: ThemeDefinition;
  deleteAccountConfirmOpen: boolean;
  deleteCurrentUserProfile?: () => void | Promise<void>;
  deleteLoan?: (id: string) => void | Promise<void>;
  displayName: string;
  firstName: string;
  headerLoans?: HeaderLoan[];
  headerProjection?: HeaderProjection;
  headerProgress?: number;
  currentUserId: string | null;
  currentUser: UserProfile | null;
  profileMenuOpen: boolean;
  setProfileMenuOpen: Dispatch<SetStateAction<boolean>>;
  profileDraftName: string;
  setProfileDraftName: Dispatch<SetStateAction<string>>;
  profileDraftEmail: string;
  setProfileDraftEmail: Dispatch<SetStateAction<string>>;
  profileStatus: string;
  passwordResetCodeInput: string;
  setPasswordResetCodeInput: Dispatch<SetStateAction<string>>;
  passwordResetNewPassword: string;
  setPasswordResetNewPassword: Dispatch<SetStateAction<string>>;
  passwordResetConfirmPassword: string;
  setPasswordResetConfirmPassword: Dispatch<SetStateAction<string>>;
  logoutUser?: () => void | Promise<void>;
  saveProfileDetails?: () => void | Promise<void>;
  applyThemeToProfile?: (themeId: ThemeId) => void | Promise<void>;
  sendPasswordResetEmail?: () => void | Promise<void>;
  applyPasswordReset?: () => void | Promise<void>;
  loanSidebarCollapsed: boolean;
  profileInitial: string;
  savedLoans: SavedLoanRecord[];
  saveStatus: string;
  setActivePage: Dispatch<SetStateAction<LoanSimulatorRuntime["activePage"]>>;
  setCreditCardTransactions: Dispatch<SetStateAction<PaymentEvent[]>>;
  setDeleteAccountConfirmOpen: Dispatch<SetStateAction<boolean>>;
  setActiveLoanTab: Dispatch<SetStateAction<LoanSimulatorRuntime["activeLoanTab"]>>;
  setActiveView: Dispatch<SetStateAction<LoanSimulatorRuntime["activeView"]>>;
  setLoanSidebarCollapsed: Dispatch<SetStateAction<boolean>>;
  startNewLoan?: (type?: "loan" | "credit-card") => void;
  loadSavedLoan?: (id: string) => void;
  profileMenuRef: RefObject<HTMLDivElement | null>;
  startingPrincipalDate: string;
  minimumPayment: string;
  additionalMonthlyPayment: string;
  dueDay: string;
  targetDate: string;
  moveWeekend: boolean;
  roundDailyInterest: boolean;
  dayCountBasis: DayCountBasis;
  oneOffPayments: PaymentEvent[];
  helperPausePeriods: PausePeriod[];
  helperRecurringChanges: FutureRecurringChange[];
  helperDueDayChanges: DueDayChange[];
  deletedHelperRowIds: string[];
  helperPaymentAmountOverrides: Record<string, string>;
  paymentDateOverrides: Record<string, string>;
  paymentLabelOverrides: Record<string, string>;
  whatIfPayments: PaymentEvent[];
  whatIfRecurringChanges: FutureRecurringChange[];
  whatIfPausePeriods: PausePeriod[];
  whatIfDueDayChanges: DueDayChange[];
  deferredStartingPrincipal: string;
  deferredStartingPrincipalDate: string;
  deferredFirstPaymentDate: string;
  deferredAdditionalMonthlyPayment: string;
  deferredAprPercent: string;
  deferredDueDay: string;
  deferredTargetDate: string;
  effectiveMinimumPayment: string;
  totalMonthlyPayment: string;
  buildProjection: (...args: Parameters<typeof buildSchedule>) => ScheduleResult;
  todayDate: Date;
  todayValue: string;
  setOneOffPayments: Dispatch<SetStateAction<PaymentEvent[]>>;
  newOneOffDate: string;
  setNewOneOffDate: Dispatch<SetStateAction<string>>;
  newOneOffAmount: string;
  setNewOneOffAmount: Dispatch<SetStateAction<string>>;
  newOneOffLabel: string;
  setNewOneOffLabel: Dispatch<SetStateAction<string>>;
  setHelperPausePeriods: Dispatch<SetStateAction<PausePeriod[]>>;
  helperPauseFromMonth: string;
  setHelperPauseFromMonth: Dispatch<SetStateAction<string>>;
  helperPauseToMonth: string;
  setHelperPauseToMonth: Dispatch<SetStateAction<string>>;
  helperPauseMode: "accrues" | "paused";
  setHelperPauseMode: Dispatch<SetStateAction<"accrues" | "paused">>;
  helperBulkMode: "minimum" | "monthly-extra" | "pause" | "due-day";
  setHelperBulkMode: Dispatch<SetStateAction<"minimum" | "monthly-extra" | "pause" | "due-day">>;
  helperAdjustmentFromMonth: string;
  setHelperAdjustmentFromMonth: Dispatch<SetStateAction<string>>;
  helperAdjustmentToMonth: string;
  setHelperAdjustmentToMonth: Dispatch<SetStateAction<string>>;
  helperAdjustmentAmount: string;
  setHelperAdjustmentAmount: Dispatch<SetStateAction<string>>;
  setHelperRecurringChanges: Dispatch<SetStateAction<FutureRecurringChange[]>>;
  setHelperDueDayChanges: Dispatch<SetStateAction<DueDayChange[]>>;
  helperAdjustmentDueDay: string;
  setHelperAdjustmentDueDay: Dispatch<SetStateAction<string>>;
  setDeletedHelperRowIds: Dispatch<SetStateAction<string[]>>;
  helperActionError: string;
  setHelperActionError: Dispatch<SetStateAction<string>>;
  setHelperPaymentAmountOverrides: Dispatch<SetStateAction<Record<string, string>>>;
  setPaymentDateOverrides: Dispatch<SetStateAction<Record<string, string>>>;
  setPaymentLabelOverrides: Dispatch<SetStateAction<Record<string, string>>>;
  editingPaymentId: string;
  setEditingPaymentId: Dispatch<SetStateAction<string>>;
  editingPaymentDate: string;
  setEditingPaymentDate: Dispatch<SetStateAction<string>>;
  editingPaymentAmount: string;
  setEditingPaymentAmount: Dispatch<SetStateAction<string>>;
  editingPaymentLabel: string;
  setEditingPaymentLabel: Dispatch<SetStateAction<string>>;
  setWhatIfPayments: Dispatch<SetStateAction<PaymentEvent[]>>;
  setWhatIfRecurringChanges: Dispatch<SetStateAction<FutureRecurringChange[]>>;
  setWhatIfPausePeriods: Dispatch<SetStateAction<PausePeriod[]>>;
  whatIfEntryMode: "minimum" | "monthly-extra" | "pause" | "due-day" | "one-time";
  setWhatIfEntryMode: Dispatch<SetStateAction<"minimum" | "monthly-extra" | "pause" | "due-day" | "one-time">>;
  newWhatIfDate: string;
  setNewWhatIfDate: Dispatch<SetStateAction<string>>;
  newWhatIfAmount: string;
  setNewWhatIfAmount: Dispatch<SetStateAction<string>>;
  newWhatIfLabel: string;
  setNewWhatIfLabel: Dispatch<SetStateAction<string>>;
  whatIfAdjustmentDate: string;
  setWhatIfAdjustmentDate: Dispatch<SetStateAction<string>>;
  whatIfAdjustmentEndDate: string;
  setWhatIfAdjustmentEndDate: Dispatch<SetStateAction<string>>;
  whatIfAdjustmentAmount: string;
  setWhatIfAdjustmentAmount: Dispatch<SetStateAction<string>>;
  whatIfAdjustmentDueDay: string;
  setWhatIfAdjustmentDueDay: Dispatch<SetStateAction<string>>;
  setWhatIfDueDayChanges: Dispatch<SetStateAction<DueDayChange[]>>;
  whatIfPauseFromMonth: string;
  setWhatIfPauseFromMonth: Dispatch<SetStateAction<string>>;
  whatIfPauseToMonth: string;
  setWhatIfPauseToMonth: Dispatch<SetStateAction<string>>;
  whatIfPauseMode: "accrues" | "paused";
  setWhatIfPauseMode: Dispatch<SetStateAction<"accrues" | "paused">>;
  setWhatIfActionError: Dispatch<SetStateAction<string>>;
  whatIfActionError: string;
  whatIfMinDateValue?: string;
  addWhatIfPayment?: () => void;
  resetWhatIf?: () => void;
  loanName: string;
  setLoanName: Dispatch<SetStateAction<string>>;
  accountType: "loan" | "credit-card";
  setAccountType: Dispatch<SetStateAction<"loan" | "credit-card">>;
  promoType: "none" | "zero" | "deferred";
  setPromoType: Dispatch<SetStateAction<"none" | "zero" | "deferred">>;
  promoEndDate: string;
  setPromoEndDate: Dispatch<SetStateAction<string>>;
  cardMinimumMode: "percent" | "fixed";
  setCardMinimumMode: Dispatch<SetStateAction<"percent" | "fixed">>;
  cardMinimumPercent: string;
  setCardMinimumPercent: Dispatch<SetStateAction<string>>;
  cardMinimumFloor: string;
  setCardMinimumFloor: Dispatch<SetStateAction<string>>;
  postPromoMinimumMode: "percent" | "fixed";
  setPostPromoMinimumMode: Dispatch<SetStateAction<"percent" | "fixed">>;
  postPromoMinimumPercent: string;
  setPostPromoMinimumPercent: Dispatch<SetStateAction<string>>;
  postPromoMinimumFloor: string;
  setPostPromoMinimumFloor: Dispatch<SetStateAction<string>>;
  postPromoFixedMinimum: string;
  setPostPromoFixedMinimum: Dispatch<SetStateAction<string>>;
  cardStatementDate: string;
  setCardStatementDate: Dispatch<SetStateAction<string>>;
  setStartingPrincipal: Dispatch<SetStateAction<string>>;
  startingPrincipal: string;
  setStartingPrincipalDate: Dispatch<SetStateAction<string>>;
  firstPaymentDate: string;
  setFirstPaymentDate: Dispatch<SetStateAction<string>>;
  setMinimumPayment: Dispatch<SetStateAction<string>>;
  setAdditionalMonthlyPayment: Dispatch<SetStateAction<string>>;
  aprPercent: string;
  setAprPercent: Dispatch<SetStateAction<string>>;
  setDueDay: Dispatch<SetStateAction<string>>;
  setTargetDate: Dispatch<SetStateAction<string>>;
  setMoveWeekend: Dispatch<SetStateAction<boolean>>;
  setRoundDailyInterest: Dispatch<SetStateAction<boolean>>;
  setDayCountBasis: Dispatch<SetStateAction<DayCountBasis>>;
  saveCurrentLoan?: () => void | Promise<void>;
  targetDateMinValue?: string;
  helperMaxMonthValue?: string;
  deleteHelperPausePeriod?: (id: string) => void;
  addHelperBulkAdjustment?: () => void;
  deleteHelperRecurringChange?: (id: string) => void;
  deleteHelperDueDayChange?: (id: string) => void;
  addOneOffPayment?: () => void;
  resetHelper?: () => void;
  assumedResult: ScheduleResult;
  amortizationProjection: ScheduleResult;
  historyResult: ScheduleResult;
  helperProjection: ScheduleResult;
  whatIfProjection: ScheduleResult;
  loanInputsReady: boolean;
  historyErrors: string[];
  canShowAssumedSchedule: boolean;
  setShowAmortization: Dispatch<SetStateAction<boolean>>;
  showAmortization: boolean;
  setShowHelperAmortization: Dispatch<SetStateAction<boolean>>;
  showHelperAmortization: boolean;
  startEditingReplayRow: (row: import("./loans").ScheduleRow) => void;
  saveEditedPayment: () => void;
  cancelEditingPayment: () => void;
  deleteHelperRow: (id: string) => void;
  deleteWhatIfPayment: (id: string) => void;
  deleteWhatIfRecurringChange: (id: string) => void;
  deleteWhatIfDueDayChange: (id: string) => void;
  deleteWhatIfPausePeriod: (id: string) => void;
  showHistoricalDetails: boolean;
  setShowHistoricalDetails: Dispatch<SetStateAction<boolean>>;
  showFutureDetails: boolean;
  setShowFutureDetails: Dispatch<SetStateAction<boolean>>;
  showLifetimeDetails: boolean;
  setShowLifetimeDetails: Dispatch<SetStateAction<boolean>>;
  showComparisonDetails: boolean;
  setShowComparisonDetails: Dispatch<SetStateAction<boolean>>;
  userProfiles: UserProfile[];
  setUserProfiles: Dispatch<SetStateAction<UserProfile[]>>;
  setCurrentUserId: Dispatch<SetStateAction<string | null>>;
  authMode: "login" | "create";
  setAuthMode: Dispatch<SetStateAction<"login" | "create">>;
  authName: string;
  setAuthName: Dispatch<SetStateAction<string>>;
  authDisplayName: string;
  setAuthDisplayName: Dispatch<SetStateAction<string>>;
  authPassword: string;
  setAuthPassword: Dispatch<SetStateAction<string>>;
  authError: string;
  setAuthError: Dispatch<SetStateAction<string>>;
  setSaveStatus: Dispatch<SetStateAction<string>>;
  setProfileStatus: Dispatch<SetStateAction<string>>;
  getSavedLoansStorageKey: (userId: string) => string;
  applyLoanSnapshot: (snapshot: LoanSnapshot) => void;
  buildLoanSnapshot: () => LoanSnapshot;
  serializePaymentEvent: (event: PaymentEvent) => SerializedPaymentEvent;
  deserializePaymentEvent: (event: SerializedPaymentEvent) => PaymentEvent;
  serializeRecurringChange: (change: FutureRecurringChange) => SerializedFutureRecurringChange;
  deserializeRecurringChange: (change: SerializedFutureRecurringChange) => FutureRecurringChange;
  serializePausePeriod: (period: PausePeriod) => SerializedPausePeriod;
  deserializePausePeriod: (period: SerializedPausePeriod) => PausePeriod;
  serializeDueDayChange: (change: DueDayChange) => SerializedDueDayChange;
  deserializeDueDayChange: (change: SerializedDueDayChange) => DueDayChange;
  nextPaymentDate: string;
  minimumOnlyLifetimeInterest: number;
  assumedInterestSavedAsOfToday: number;
  helperInterestSavedAsOfToday: number;
  assumedScenarioLifetimeInterest: number;
  assumedScenarioLifetimeSaved: number;
  assumedScenarioRemainingInterest: number;
  assumedScenarioRemainingSaved: number;
  helperScenarioLifetimeInterest: number;
  helperScenarioLifetimeSaved: number;
  helperScenarioRemainingInterest: number;
  helperScenarioRemainingSaved: number;
  whatIfProjectedExtrasSavedRemaining: number;
  whatIfScenarioRemainingInterest: number;
  whatIfScenarioLifetimeInterest: number;
  whatIfScenarioSaved: number;
  activePayoffPercent: number;
  activeProjectedPayoffDate: Date | null;
  activeDailyInterestCost: number;
  activePayoffDuration: string;
  activeTimeSavedLabel: string;
  softDangerMessage: string | null;
  whatIfDeltaInterest: number;
  whatIfBaselinePayoffDate: Date | null;
  whatIfTimeChangeLabel: string;
  assumedLifetimeSavedTone: string;
  helperLifetimeSavedTone: string;
  whatIfLifetimeSavedTone: string;
  assumedRemainingInterestNotes: number[];
  assumedRemainingSavedNotes: number[];
  assumedLifetimeSavedNotes: number[];
  helperRemainingInterestNotes: number[];
  helperRemainingSavedNotes: number[];
  helperLifetimeSavedNotes: number[];
  whatIfRemainingInterestNotes: number[];
  whatIfAdditionalSavedNotes: number[];
  whatIfLifetimeSavedNotes: number[];
  footnote2Text: string;
  negativeAmortizationWarning: boolean;
}
