import { useEffect, useState } from "react";
import { CurrencyField } from "../components/ui/CurrencyField";
import { SummaryValue } from "../components/ui/summary";
import { simulatePortfolio, type PortfolioStrategy } from "../calculations/debt/simulatePortfolio";
import { estimateSavedLoanBalance, estimateSavedAccountMinimum } from "../calculations/debt/savedAccount";
import { parseCurrency } from "../utils/currency";
import { formatCurrency, formatMonthYear, formatPercent } from "../utils/formatting";
import type { SavedLoanRecord } from "../types/loans";
import type { ThemeDefinition } from "../constants/theme";
export function DebtOverview({ loans, theme, userId }: { loans: SavedLoanRecord[]; theme: ThemeDefinition; userId: string }) {
  const [extraPayment, setExtraPayment] = useState("0.00");
  const [strategy, setStrategy] = useState<PortfolioStrategy>("avalanche");
  const budgetKey = `loan-sim:budget:${userId}`;
  const [bills, setBills] = useState<Array<{ id: string; name: string; category: string; amount: number }>>(() => { try { return JSON.parse(localStorage.getItem(budgetKey) ?? "[]") as Array<{ id: string; name: string; category: string; amount: number }>; } catch { return []; } });
  const [billName, setBillName] = useState("");
  const [billCategory, setBillCategory] = useState("Utilities");
  const [billAmount, setBillAmount] = useState(0);
  const [monthlyIncome, setMonthlyIncome] = useState(0);
  useEffect(() => { localStorage.setItem(budgetKey, JSON.stringify(bills)); }, [budgetKey, bills]);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(`loan-sim:paycheck-scenarios:${userId}`) ?? "null") as { scenarios?: Array<{ incomeType?: string; inputs?: { annualSalary?: number }; hourlyRate?: number; hoursPerWeek?: number }> } | null; const scenarios = saved?.scenarios ?? []; setMonthlyIncome(scenarios.reduce((sum, s) => sum + (s.incomeType === "hourly" ? (s.hourlyRate ?? 0) * (s.hoursPerWeek ?? 0) * 52 / 12 : (s.inputs?.annualSalary ?? 0) / 12), 0)); } catch { setMonthlyIncome(0); } }, [userId]);
  const portfolioLoans = loans.map((loan) => ({ id: loan.id, name: loan.name, balance: estimateSavedLoanBalance(loan.data), apr: Number(loan.data.aprPercent) || 0, minimum: estimateSavedAccountMinimum(loan.data) })).filter((loan) => loan.balance > 0 && loan.minimum > 0);
  const extra = parseCurrency(extraPayment);
  const results = {
    avalanche: simulatePortfolio(portfolioLoans, "avalanche", extra),
    snowball: simulatePortfolio(portfolioLoans, "snowball", extra),
    minimum: simulatePortfolio(portfolioLoans, "minimum", 0),
  };
  const selected = results[strategy];
  const totalOriginal = loans.reduce((sum, loan) => sum + (loan.data.overviewOriginalBalance ?? parseCurrency(loan.data.startingPrincipal)), 0);
  const progress = totalOriginal > 0 ? Math.max(0, Math.min(100, (1 - selected.startingTotal / totalOriginal) * 100)) : 0;
  return <main style={{ display: "grid", gap: 20 }}>
    <section style={{ background: theme.surface, border: `1px solid ${theme.cardBorder}`, borderRadius: 18, padding: 22, boxShadow: theme.cardShadow, display: "grid", gap: 18 }}><div><h2 style={{ margin: 0 }}>Overall debt plan</h2><p style={{ margin: "6px 0 0", color: theme.textMuted }}>Compare payoff order across every saved loan. Add an extra monthly amount to see how each strategy changes interest and payoff timing.</p></div>{portfolioLoans.length === 0 ? <div style={{ padding: 18, border: `1px dashed ${theme.cardBorder}`, borderRadius: 12, color: theme.textMuted }}>Save at least one loan to build an overall payoff plan.</div> : <><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))", gap: 12 }}><SummaryValue label="Remaining debt" value={formatCurrency(selected.startingTotal)} emphasized /><SummaryValue label="Estimated payoff" value={formatMonthYear(selected.payoffDate)} emphasized /><SummaryValue label="Payoff progress" value={formatPercent(progress)} emphasized /></div><div style={{ height: 9, borderRadius: 999, overflow: "hidden", background: theme.surfaceMuted }}><div style={{ width: `${progress}%`, height: "100%", background: theme.accent }} /></div></>}</section>
    {portfolioLoans.length > 0 ? <><section style={{ background: theme.surface, border: `1px solid ${theme.cardBorder}`, borderRadius: 18, padding: 20, boxShadow: theme.cardShadow, display: "grid", gap: 16 }}><div style={{ maxWidth: 280 }}><CurrencyField id="portfolio-extra" label="Extra available for debt each month" value={extraPayment} onChange={setExtraPayment} /></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 12 }}>{(["avalanche", "snowball", "minimum"] as const).map((method) => <button key={method} type="button" onClick={() => setStrategy(method)} style={{ border: `1px solid ${strategy === method ? theme.accent : theme.cardBorder}`, borderRadius: 14, padding: 14, background: strategy === method ? theme.accentSoft : theme.surface, color: theme.text, textAlign: "left", cursor: "pointer", display: "grid", gap: 6 }}><strong>{method === "avalanche" ? "Debt avalanche" : method === "snowball" ? "Debt snowball" : "Minimum payments"}</strong><span style={{ fontSize: 12, color: theme.textMuted }}>{method === "avalanche" ? "Highest APR first" : method === "snowball" ? "Smallest balance first" : "No targeted extra payment"}</span><span style={{ fontSize: 13 }}>{formatCurrency(results[method].totalInterest)} interest · {results[method].months} months</span></button>)}</div></section>
    <section style={{ background: theme.surface, border: `1px solid ${theme.cardBorder}`, borderRadius: 18, padding: 20, boxShadow: theme.cardShadow, overflow: "hidden" }}><h3 style={{ margin: "0 0 14px" }}>Loans</h3><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr>{["Loan", "Balance", "APR", "Monthly payment", "Priority"].map((heading) => <th key={heading} style={{ padding: 9, textAlign: "left", borderBottom: `1px solid ${theme.cardBorder}`, color: theme.textMuted, fontSize: 12 }}>{heading}</th>)}</tr></thead><tbody>{[...portfolioLoans].sort((a, b) => strategy === "avalanche" ? b.apr - a.apr : strategy === "snowball" ? a.balance - b.balance : 0).map((loan, index) => <tr key={loan.id}><td style={{ padding: 10, borderBottom: `1px solid ${theme.cardBorder}`, fontWeight: 650 }}>{loan.name}</td><td style={{ padding: 10, borderBottom: `1px solid ${theme.cardBorder}` }}>{formatCurrency(loan.balance)}</td><td style={{ padding: 10, borderBottom: `1px solid ${theme.cardBorder}` }}>{formatPercent(loan.apr)}</td><td style={{ padding: 10, borderBottom: `1px solid ${theme.cardBorder}` }}>{formatCurrency(loan.minimum)}</td><td style={{ padding: 10, borderBottom: `1px solid ${theme.cardBorder}` }}>{strategy === "minimum" ? "—" : index + 1}</td></tr>)}</tbody></table></section>
    <section style={{ background: theme.surface, border: `1px solid ${theme.cardBorder}`, borderRadius: 18, padding: 20, boxShadow: theme.cardShadow, overflowX: "auto" }}><h3 style={{ margin: "0 0 14px" }}>Next 12 months</h3><table style={{ borderCollapse: "collapse", minWidth: 980, width: "100%" }}><thead><tr><th style={{ position: "sticky", left: 0, background: theme.surface, padding: 8, textAlign: "left" }}>Loan</th>{selected.snapshots.map((snapshot) => <th key={snapshot.date.toISOString()} style={{ padding: 8, fontSize: 11, color: theme.textMuted }}>{snapshot.date.toLocaleString("en-US", { month: "short", year: "2-digit" })}</th>)}</tr></thead><tbody>{portfolioLoans.map((loan) => <tr key={loan.id}><td style={{ position: "sticky", left: 0, background: theme.surface, padding: 8, fontWeight: 650 }}>{loan.name}</td>{selected.snapshots.map((snapshot) => <td key={snapshot.date.toISOString()} style={{ padding: 8, fontSize: 12, borderTop: `1px solid ${theme.cardBorder}` }}>{formatCurrency(snapshot.balances[loan.id] ?? 0)}</td>)}</tr>)}</tbody></table></section></> : null}
    <section style={{ background: theme.surface, border: `1px solid ${theme.cardBorder}`, borderRadius: 18, padding: 20, boxShadow: theme.cardShadow, display: "none" }}><div><h3 style={{ margin: 0 }}>Monthly budget</h3><p style={{ margin: "5px 0 0", color: theme.textMuted, fontSize: 13 }}>Track recurring bills so the extra amount going to debt reflects real cash flow.</p></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 10 }}><input value={billName} onChange={(event) => setBillName(event.target.value)} placeholder="Bill name" style={{ padding: 10, borderRadius: 9, border: `1px solid ${theme.cardBorder}` }} /><input value={billCategory} onChange={(event) => setBillCategory(event.target.value)} placeholder="Category" style={{ padding: 10, borderRadius: 9, border: `1px solid ${theme.cardBorder}` }} /><input type="number" value={billAmount || ""} onChange={(event) => setBillAmount(Number(event.target.value) || 0)} placeholder="Monthly amount" style={{ padding: 10, borderRadius: 9, border: `1px solid ${theme.cardBorder}` }} /><button type="button" onClick={() => { if (!billName.trim() || billAmount <= 0) return; setBills((current) => [...current, { id: crypto.randomUUID(), name: billName.trim(), category: billCategory.trim() || "Other", amount: billAmount }]); setBillName(""); setBillAmount(0); }} style={{ border: 0, borderRadius: 9, background: theme.accent, color: "#fff", fontWeight: 700, cursor: "pointer" }}>Add bill</button></div><div style={{ display: "grid", gap: 7 }}>{bills.map((bill) => <div key={bill.id} style={{ display: "flex", justifyContent: "space-between", gap: 12, padding: "9px 11px", borderRadius: 9, background: theme.surfaceMuted }}><span>{bill.name} <small style={{ color: theme.textMuted }}>({bill.category})</small></span><span><strong>{formatCurrency(bill.amount)}</strong> <button type="button" onClick={() => setBills((current) => current.filter((item) => item.id !== bill.id))} style={{ marginLeft: 8, border: 0, background: "transparent", color: "#b91c1c", cursor: "pointer" }}>×</button></span></div>)}</div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))", gap: 10 }}><SummaryValue label="Estimated monthly income" value={monthlyIncome ? formatCurrency(monthlyIncome) : "Add a pay estimate"} /><SummaryValue label="Monthly bills" value={formatCurrency(bills.reduce((sum, bill) => sum + bill.amount, 0))} /><SummaryValue label="After bills and minimums" value={monthlyIncome ? formatCurrency(monthlyIncome - bills.reduce((sum, bill) => sum + bill.amount, 0) - portfolioLoans.reduce((sum, loan) => sum + loan.minimum, 0)) : "—"} /></div></section>
   </main>;
}

